quarkus:
  http:
    port: 8080

  datasource:
    db-kind: postgresql
    username: ${PG_USER}
    password: ${PG_PWD}
    jdbc:
      url: jdbc:postgresql://${PG_HOST_NAME:localhost}:${PG_HOST_PORT:5432}/covid19_italy?currentSchema=public
      max-size: 10
      min-size: 5

  hibernate-orm:
    dialect:  io.quarkus.hibernate.orm.runtime.dialect.QuarkusPostgreSQL10Dialect

  liquibase:
    change-log: db/master.yml
    migrate-at-start: true

  smallrye-openapi:
    path: /openapi-test

  swagger-ui:
    always-include: true
    enable: true
    path: /swagger-openapi


  log:
    console:
#      async: true
      enable: true
      level: DEBUG
    file:
      enable: true
#      async: true
      level: DEBUG
      path: ${LOG_DIR:..}/quarkus-performace-tests.log
    level: FINEST

#
#  package:
#    type: uber-jar

  native:
#     builder-image: davidemartorana/mandrel-native-static:centos8
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel:20.2-java11
    native-image-xmx: 8g

cron:
  scheduler:
    expr: "0  0/1  * * * ?"       # This works like a charm
#    expr: "0 0/60 * * * ?"     This does not work fails with error: java.lang.IllegalArgumentException: Period 60 not in range [0, 59]

