server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    username: ${PG_USER}
    password: ${PG_PWD}
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/covid19_italy?currentSchema=public

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
